language: generic
script:
  - ./update.sh
env:
  global:
    - GIT_AUTHOR_NAME="Travis CI"
    - GIT_AUTHOR_EMAIL="travis@easyb.ch"
    - GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
    - GIT_COMMITTER_EMAIL="$GIT_COMMITTER_EMAIL"
