language: generic
before_install:
  - sudo apt install -y heirloom-mailx
addons:
  apt:
    update: true
script:
  - ./update.sh
env:
  global:
    - GIT_AUTHOR_NAME="Travis CI"
    - GIT_AUTHOR_EMAIL="travis@easyb.ch"
    - GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
    - GIT_COMMITTER_EMAIL="$GIT_COMMITTER_EMAIL"
